extends Resource
class_name SpecialEffect

enum SPECIAL_EFFECT
{
	#WEAPON SPECIALS
	WEAPON_TRIANGLE_ADVANTAGE_EFFECTIVE,
	CRITICAL_DISABLED,
	NEGATES_FOE_DEFENSE,
	NEGATES_FOE_DEFENSE_ON_CRITICAL,
	CANNOT_RETALIATE,
	DEVIL_REVERSAL,
	#WEAPON SPECIAL THAT REQUIRE VALUE
	VAMPYRIC,
	#ITEM SPECIALS
	CRITICAL_PROOF, 
	EFFECTIVE_PROOF,
	CANNOT_DO_EFFECTIVE_DAMAGE,
	REMOVE_FLIER_EFFECTIVE,
	ADD_FLIER_EFFECTIVE,
	ADD_FLIER_EFFECTIVE_ATTACK,
	REMOVE_ARMOR_EFFECTIVE,
	ADD_ARMOR_EFFECTIVE,
	ADD_ARMOR_EFFECTIVE_ATTACK,
	REMOVE_MOUNTED_EFFECTIVE,
	ADD_MOUNTED_EFFECTIVE,
	ADD_MOUNTED_EFFECTIVE_ATTACK,
	REMOVE_TERROR_EFFECTIVE,
	ADD_TERROR_EFFECTIVE,
	ADD_TERROR_EFFECTIVE_ATTACK,
	ALL_DAMAGE_TYPE_MAGIC, #TODO
	ALL_DAMAGE_TYPE_PHYSICAL, #TODO
	ALL_DAMAGE_TYPE_TRUE, #TODO
	#ITEM SPECIAL THAT REQUIRE VALUE
	HEAL_ON_TURN_BEGIN,
	HEAL_ON_TURN_END,
	HEAL_ON_COMBAT_EXCHANGE_END,
	INCOMING_HEALING_AUGMENT, # ADD OR REMOVE
	INCOMING_DAMAGE_AUGMENT, # ADD OR REMOVE
	THORNS,
}

enum SPECIAL_EFFECT_WEIGHT_TYPE {
	FLAT_VALUE,
	PERCENTAGE
}

enum SPECIAL_EFFECT_ACTIVATION_TYPE {
	RANDOM_CHANCE, #percent chance
	UNIT_STAT_HP,
	UNIT_STAT_STRENGTH,
	UNIT_STAT_MAGIC,
	UNIT_STAT_SKILL,
	UNIT_STAT_SPEED,
	UNIT_STAT_LUCK,
	UNIT_STAT_DEFENSE,
	UNIT_STAT_RESISTANCE,
	UNIT_STAT_MOVEMENT,
	UNIT_STAT_CONSITUTION,
}

# This is what special is being held
@export var special : SPECIAL_EFFECT

#The power of the said effect if it is configurable
@export_group("Effect Weight Info")
@export var effect_weight : int
@export var effect_type : SPECIAL_EFFECT_WEIGHT_TYPE = SPECIAL_EFFECT_WEIGHT_TYPE.FLAT_VALUE

@export_group("Effect Activation Details")
@export var always_active : bool = true
@export var activation_type : SPECIAL_EFFECT_ACTIVATION_TYPE = SPECIAL_EFFECT_ACTIVATION_TYPE.RANDOM_CHANCE
@export var activation_threshold : float = 100
