extends Resource

class_name EventOption

enum EVENT_EFFECT{
	STRENGTH_ALL,
	MAGIC_ALL,
	RANDOM_WEAPON,
	RANDOM_CONSUMABLE,
	FLEE,
	BANDIT_BRIBE,
	BANDIT_FIGHT,
	BANDIT_INTIMIDATE,
	TRIAL_MEDITATE,
	TRIAL_CUT_PATH,
	TRIAL_RUSH_THROUGH,
	GOBLET_DRINK,
	GOBLET_SPILL,
}

@export var description : String
@export var effect : EVENT_EFFECT
